### ISSUE TITLE
docker-compose up  error

### ISSUE THREAD

**Issue by wsdo** [codemix/yii2-dockerized#11]
![image](https://user-images.githubusercontent.com/9738969/33513401-fe971d32-d77c-11e7-975d-bce7c2251253.png)
![image](https://user-images.githubusercontent.com/9738969/33513404-0578e1b2-d77d-11e7-9306-b9b6b6b755cf.png)

**Comment by mikehaertl** [comment]
This is because V3 of the docker compose file specs doesn't support `volumes_from` anymore. Either change back to `version: '2'` on top of that file or simply add the same `volumes` block for your nginx container:

```
volumes:
    - ./:/var/www/html
```

It also seems you're using our old template, right? As you may have seen, we've completely revamped the setup now. Maybe you want to try it.
